"""Bump memories content limit 32k -> 200k; allow NULL embedding.

Revision ID: 0011_embedding_nullable
Revises: 0010_memory_clusters
Create Date: 2026-05-19

Two changes:

1. Drop NOT NULL on memories.embedding. Bedrock Titan embeddings cap at
   ~8K tokens (~32K chars); for oversize content we skip the embed call
   and store NULL. Semantic search drops NULL-embedding rows via new
   IS NOT NULL guards; keyword search still surfaces them.

2. Replace the inline CHECK constraint `length(content) BETWEEN 1 AND 32768`
   with `BETWEEN 1 AND 200000`. Without this, INSERTs of memories larger
   than the old 32K limit would fail at the DB layer regardless of Pydantic
   accepting them.
"""

import sqlalchemy as sa

from alembic import op

revision = "0011_embedding_nullable"
down_revision = "0010_memory_clusters"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Drop NOT NULL on embedding so oversize-content rows can store NULL.
    op.execute(sa.text("ALTER TABLE memories ALTER COLUMN embedding DROP NOT NULL"))

    # Replace the content-length CHECK constraint. PostgreSQL doesn't let us
    # alter a CHECK in place — we drop and recreate. The constraint name
    # was auto-generated by the initial CREATE TABLE; find it dynamically
    # so we don't depend on the implicit name.
    op.execute(
        sa.text(
            """
            DO $$
            DECLARE
                cname TEXT;
            BEGIN
                SELECT conname INTO cname
                FROM pg_constraint
                WHERE conrelid = 'memories'::regclass
                  AND contype = 'c'
                  AND pg_get_constraintdef(oid) LIKE '%length(content)%';
                IF cname IS NOT NULL THEN
                    EXECUTE format('ALTER TABLE memories DROP CONSTRAINT %I', cname);
                END IF;
            END $$;
            """
        )
    )
    op.execute(
        sa.text(
            "ALTER TABLE memories "
            "ADD CONSTRAINT memories_content_length_check "
            "CHECK (length(content) BETWEEN 1 AND 200000)"
        )
    )


def downgrade() -> None:
    # Reverting embedding NOT NULL requires backfilling NULLs with a
    # placeholder vector first — leave that to the operator since the
    # choice of placeholder is policy.
    op.execute(sa.text("ALTER TABLE memories ALTER COLUMN embedding SET NOT NULL"))
    op.execute(
        sa.text(
            "ALTER TABLE memories DROP CONSTRAINT IF EXISTS memories_content_length_check"
        )
    )
    op.execute(
        sa.text(
            "ALTER TABLE memories "
            "ADD CONSTRAINT memories_content_length_check "
            "CHECK (length(content) BETWEEN 1 AND 32768)"
        )
    )
